language: python
python:
  - '3.5'
branches:
  only:
    - pre-production

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pydomus_project.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
